name: Format

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm bs format:check
